%% Init
close all;
clear;
clc

%% Parameters
x = linspace(0, 2 * pi, 10);
y = sin(x);

%% Figure
h_fig = figure;
set(h_fig, ...
    'Name', 'Name', ...
    'NumberTitle', 'off', ...
    'Units', 'normalized', ...
    'Position', [0.25, 0.25, 0.5, 0.5], ...
    'Color', 'White' ...
);

%% Axes
h_ax = axes(h_fig);
    

%% Plot
h_plot = line(h_ax, x, sin(x));
set(h_plot, ...
    'Color', [1, 0, 0], ...
    'LineStyle', '-', ...
    'LineWidth', 2, ...
    'Marker', 'o', ...
    'MarkerSize', 10, ...
    'MarkerEdgeColor', [0, 1, 0], ...
    'MarkerFaceColor', [0, 0, 1], ...
    'DisplayName', 'Sin' ...
);

%% Axes
set(h_ax, ...
    'Box', 'off', ...
    'Color', [0.9, 0.9, 0.9], ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'Xlim', [0, 6], ...
    'XminorGrid', 'on' ....
);
title('Sin')
xlabel('x')
ylabel('y')

